"""updated the schema

Revision ID: 1b422e1e21fc
Revises: 3c503453314e
Create Date: 2026-03-09 12:02:41.872464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b422e1e21fc'
down_revision: Union[str, Sequence[str], None] = '3c503453314e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user_table', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'expires_at')
    op.drop_column('user_table', 'created_at')
    # ### end Alembic commands ###
